# Variables to use specific to localhost (for working with APIs)
all:
  hosts:
    localhost:
      # Since there are multiple physical groups of systems I specify
      # a grouping of equipment to use for naming the nPod. This is unique
      # per inventory.
      equipment: "lenovo"
      # How to wait (in minutes) for hosts to boot after nPod creation
      wait_hosts: 3
      # Credential values mapped from the ../../credentials.yml file
      # nebulon ON credentials
      neb_username: "{{ vault_neb_username }}"
      neb_password: "{{ vault_neb_password }}"

      # # SSH password to use (in place of specifying --ask-pass)
      # ansible_password: "{{ vault_ansible_password }}"

# Physical server inventory
servers:
  hosts: 
  # Currently, each host has spu_serial and spu_address specified here
  # in the inventory. This will be moved out to a config file once the
  # spu_lookup module is completed.
    server-09.tme.nebulon.com:
      spu_serial: 012386435A39449519 
      spu_address: 10.100.29.117
    server-10.tme.nebulon.com: 
      spu_serial: 01231C5BA68435FC19 
      spu_address: 10.100.29.118
    server-11.tme.nebulon.com: 
      spu_serial: 01234C1DDA95332EEE 
      spu_address: 10.100.29.119
    server-12.tme.nebulon.com: 
      spu_serial: 01236AE13059FD35EE 
      spu_address: 10.100.29.120
##### /VMware Bare Metal #####

##### K8s Inventory #####
# Physical inventory for bare metal K8s deployments
k8s:
  hosts:
    server-09.tme.nebulon.com:
    server-10.tme.nebulon.com:
    server-11.tme.nebulon.com:
    server-12.tme.nebulon.com:    
  children:
    k8s_master:
      hosts:
        server-09.tme.nebulon.com:
    k8s_nodes:
      hosts:
        server-10.tme.nebulon.com:
        server-11.tme.nebulon.com:
        server-12.tme.nebulon.com:
##### /K8s Inventory #####